### ISSUE TITLE
Leeg mutaties bestand

### ISSUE THREAD

**Issue by jeroenwilms** [HippoHR/rabo-to-xero#1]
Het mutaties bestand komt steeds leeg terug. Waar kan dit aan liggen? Wat kan ik er aan doen? Wil graag in Xero kunnen reconcilen en heb daar deze statements voor nodig...

**Comment by ghost** [comment]
Bedankt voor de melding, Jeroen. Wij ervaren zelf op dit moment geen problemen.

Probeer je dit script nu voor het eerst, of gebruik je het al langer en ervaar je dit probleem pas sinds kort? 
Zijn er foutmeldingen die je ziet? Misschien vind je errors in de Apache error log?
Welke versie van PHP gebruik je?
