### ISSUE TITLE
Gebruik

### ISSUE THREAD

**Issue by jeeyer** [HippoHR/rabo-to-xero#3]
Hi!

Ik ben erg geïnteresseerd om dit script te gebruiken. 
Hoe kan ik het het beste toepassen? Werkt een site als: http://www.runphponline.com/ ?

Heb hier weinig ervaring mee (sorry!).

Of moet ik echt WAMP server oid opzetten? Alvast bedankt voor de hulp!
Groet. Joost

**Comment by dbroeks** [comment]
Om dit script te gebruiken, zul je PHP en een webserver (Apache bijvoorbeeld) nodig hebben. Het is niet nodig om de hele WAMP-stack te gebruiken. Apache + PHP is genoeg. 

Het is wel het makkelijkste om WAMP te installeren, dan werkt alles out of the box. Sla het script op, plaats het in de juiste map, zorg dat Apache draait, en ga naar http://localhost/rabo_to_xero.php in je browser.
